using System;
using System.Collections.Generic;

namespace RemotableObjects
{

    [Serializable]
    public class Message
    {

        /**
         * Unique ID. (UUID?)
         */
        public string Id {get; set;}

        /**
         * Content.
         */
        public string Text {get; set;}

        /**
         * ISO DateTime with timezone indicator (ISO 8601)
         */
        public string Timestamp {get; set;}

        // ---

        public Message(string text)
        {
            this.Text = text;
        }

        // ---

        // The Equals and GetHashCode methods were automatically generated by Visual Studio 2019 (Version 16.8.4).
        // I manually wrote the following commented out Equals method, and originally didn't override GetHashCode.
        /*
        public override bool Equals(object obj)
        {
            Message otherMessage = (Message)obj;
            // return otherMessage != null && otherMessage.id != null && otherMessage.id.Equals(this.id);
            bool? hasSameId = otherMessage?.Id?.Equals(this.Id);
            return hasSameId ?? false;
        }
        */

        public override bool Equals(object obj)
        {
            return obj is Message message &&
                   Id == message.Id;
        }

        public override int GetHashCode()
        {
            return 2108858624 + EqualityComparer<string>.Default.GetHashCode(Id);
        }

    }

}
